# Generated by Django 4.1.7 on 2023-04-14 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Computing', 'computing'), ('Electronics', 'electronics'), ('Sporting Goods', 'sporting goods'), ('Fashion', 'fashion'), ('Automobile', 'automobile'), ('Toys and Games', 'toys and games'), ('Phones and Tablets', 'phones and tablets'), ('Musical Instruments', 'Musical instruments')], max_length=255)),
                ('category_description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateField(auto_now=True)),
                ('sales_tax', models.FloatField()),
                ('Fullfilled', models.BooleanField(default=False)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.FloatField()),
                ('size', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem')),
            ],
        ),
    ]
