# Generated by Django 4.1.7 on 2023-04-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_customer_alter_product_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Fullfilled',
            new_name='fullfilment_status',
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
