# Generated by Django 4.1.7 on 2023-04-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Computing', 'computing'), ('Electronics', 'electronics'), ('Sporting Goods', 'sporting goods'), ('Fashion', 'fashion'), ('Automobile', 'automobile'), ('Toys and Games', 'toys and games'), ('Phones and Tablets', 'phones and tablets'), ('Musical Instruments', 'Musical instruments')], max_length=100, null=True),
        ),
    ]
