# Generated by Django 4.1.7 on 2023-04-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_category_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
