# Generated by Django 4.1.7 on 2023-04-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
